spring:
  datasource:
    url: jdbc:h2:./eStoreDB
    username: jk
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true


